### ISSUE TITLE
nothing shows

### ISSUE THREAD

**Issue by hwj0629** [jmfridey/COC-Clan-Page#2]
i have set the token and tag but nothing in page.
[https://www.hwj6.cn/COC](https://www.hwj6.cn/COC)

**Comment by hwj0629** [comment]
besides could you teach me
why [https://www.hwj6.cn/clan1.php](https://www.hwj6.cn/clan1.php) is ok
but  [https://www.hwj6.cn/clan.php](https://www.hwj6.cn/clan.php) error 500
the code and token is same i just change the tag

**Comment by IldeNet** [comment]
It does not work for me

**Comment by lroe** [comment]
> besides could you teach me
why https://www.hwj6.cn/clan1.php is ok
but https://www.hwj6.cn/clan.php error 500
the code and token is same i just change the tag

Dude, you should change the token with your own token. Go to CoC developers site and create a new API (make sure to whitelist your host IP) and apply that token. It is completely working :')
